#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=1.6.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend dottee.tech
        bind 0:80
        default_backend web_servers
backend web_servers
        balance roundrobin
        server 135930-web-01 34.202.159.33
        server 135930-web-02 54.81.203.100
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
